### ISSUE TITLE
Data file approach (thread reference to prisma/prisma-label-sync)

### ISSUE THREAD

**Issue by maticzav** [maticzav/label-sync#75]
https://github.com/prisma/prisma-label-sync/issues/62

**Comment by jasonkuhrt** [comment]
I'm personally happy now with the system. Example of how I have come to use it: https://github.com/prisma-labs/prisma-labs-labelsync/blob/master/labelsync.ts. I do think there is room for improvement on the TS lib side, but that is a different topic.

Given there is now `labelsync.yml` what is there left to discuss?

**Comment by maticzav** [comment]
@jasonkuhrt I think it would be neat if you could define labels in one place and then have types generated so that the tool would suggest names from the "pool". What do you think?

Besides that, do you like the experience with the programmatic approach so far? I can't decide whether it's good enough yet to create a "public" announcement of the tool.

**Comment by jasonkuhrt** [comment]
I personally created my own wrapper around the library. Feel free to take a look. The current lib doesn't really meet my needs, maybe there are more features I have yet to discover though. Basically I just wanted something a bit simpler.

I think the programatic approach makes sense but certainly a higher bar to entry, and maybe a big turn off for non TS-users, e.g. Go Python etc. users who may have never touched TypeScript, `tsconfig.json`, `package.json` etc.

To make your tool have as widespread adoption as possible, I would suggest it begins language agnostic for the user, but a TypeScript bootstrap PR is made allowing users to opt int right away.

**Comment by jasonkuhrt** [comment]
Actually I could imagine one day where the aforementioned PR has checkboxes for different languages, and the user can just pick the one that they prefer. Programatic label management isn't so crazy after all right? You just need to provide a way to manage labels (name color description) and repo groupings. Basically variables dicts and lists... You could probably somewhat easily support single handedly 3-5 major languages for such a simple kind of data management? 

You could probably use the Org's stats to figure out which language to default the PR to, rather than assuming TS.
